#!/usr/bin/env bash
set -euo pipefail

MAIN=$(git rev-parse --abbrev-ref HEAD)
NUM=$(echo "$ISSUE_JSON" | jq -r '.number')
TITLE=$(echo "$ISSUE_JSON" | jq -r '.title')
BODY=$(echo "$ISSUE_JSON" | jq -r '.body')
BRANCH="auto-fix/issue-${NUM}"

echo "=== #${NUM}: ${TITLE} ==="

# Rollback label on failure
cleanup_on_failure() {
  gh issue edit "$NUM" --repo "$REPO" --add-label auto-fix --remove-label auto-fix-in-progress 2>/dev/null || true
}
trap cleanup_on_failure ERR

# Skip if PR exists
if [ "$(gh pr list --repo "$REPO" --head "$BRANCH" --json number --jq 'length')" -gt 0 ]; then
  echo "PR exists, skip"
  gh issue edit "$NUM" --repo "$REPO" --add-label auto-fix-done --remove-label auto-fix-in-progress
  exit 0
fi

# Build model args
GEN_MODEL_ARG=""
[ -n "${GENERATOR_MODEL:-}" ] && GEN_MODEL_ARG="--model $GENERATOR_MODEL"
REV_MODEL_ARG=""
[ -n "${REVIEWER_MODEL:-}" ] && REV_MODEL_ARG="--model $REVIEWER_MODEL"

git checkout -b "$BRANCH"

# Step 1: Generate fix
evot -p "Fix this issue in databend-docs by modifying files under docs/en/.
Follow existing doc style. Read related files first.

The Databend source code is available at _databend/src/ for reference.
Use it to check actual implementation details (settings, functions, SQL syntax, etc.)
when writing documentation.

Issue #${NUM}: ${TITLE}
${BODY}" \
  $GEN_MODEL_ARG \
  --max-turns 30 --max-duration 600 || true

if git diff --quiet; then
  echo "No changes"
  cleanup_on_failure
  exit 0
fi

# Step 2: Review loop (max 2 rounds)
APPROVED=false
for round in 1 2; do
  DIFF=$(git diff)
  [ -z "$DIFF" ] && { APPROVED=true; break; }

  REVIEW=$(evot -p "Review this diff for issue #${NUM}: ${TITLE}
${BODY}

Respond ONLY with JSON: {\"approved\": bool, \"comments\": \"...\"}

${DIFF}" \
    $REV_MODEL_ARG \
    --max-turns 1 --max-duration 60 2>&1 || true)

  if echo "$REVIEW" | grep -q '"approved"[[:space:]]*:[[:space:]]*true'; then
    APPROVED=true; break
  fi

  COMMENTS=$(echo "$REVIEW" | python3 -c "
import sys,json,re
t=sys.stdin.read(); m=re.search(r'\{[^}]*\}',t,re.DOTALL)
try: print(json.loads(m.group())['comments']) if m else print(t[:500])
except: print(t[:500])" 2>/dev/null || echo "$REVIEW" | head -10)

  evot -p "Address this review for issue #${NUM}:
${COMMENTS}" \
    $GEN_MODEL_ARG \
    --max-turns 20 --max-duration 300 || true
done

# Step 3: PR
git add -A
git commit -m "docs: auto-fix #${NUM}" || { cleanup_on_failure; exit 0; }
git push origin "$BRANCH" --force

STATUS=$( [ "$APPROVED" = true ] && echo "✅ Approved" || echo "⚠️ Needs human review" )
gh pr create --repo "$REPO" --base "$MAIN" --head "$BRANCH" \
  --title "docs: auto-fix #${NUM}" \
  --body "Fixes #${NUM}. ${STATUS}
Generated by \`${GENERATOR_MODEL}\`, reviewed by \`${REVIEWER_MODEL}\`." \
  --label auto-fix || true

# Mark done
gh issue edit "$NUM" --repo "$REPO" --add-label auto-fix-done --remove-label auto-fix-in-progress
