plugins:
  - remark-validate-links
  - [
    remark-lint-no-dead-urls,
    {
      skipLocalhost: true,
      skipUrlPatterns:
        [
          '/^https:\/\/(.*)github\.com/',
          /^https:\/\/link\.databend\.rs/,
          /^https:\/\/(.*)vldb\.org/,
          /^https:\/\/(.*)arxiv\.org/,
          /^https:\/\/asciinema\.org/,
          "https://asciinema.org",
          "https://github.com",
          "https://link.databend.com",
        ],
      gotOptions:
        {
          concurrency: 1,
          timeout:
            {
              lookup: 100,
              connect: 100,
              secureConnect: 50,
              socket: 1000,
              send: 5000,
              response: 1000,
            },
        },
    },
  ]
# https://github.com/remarkjs/remark-lint/blob/main/doc/rules.md
