name: GPT Translate Sync

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  pull-requests: write
  checks: write
  statuses: write
  contents: write

jobs:
  gpt_translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Delete unsync files
        id: delete_unsync
        run: |
          chmod +x ./scripts/delete_unsync.sh
          source ./scripts/delete_unsync.sh

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: "chore: delete unsync files"
          push: false

      - name: Check missing files
        id: check_missing
        run: |
          chmod +x ./scripts/check_missing.sh
          source ./scripts/check_missing.sh
          echo "missing_md_files=$(echo $missing_md_files | tr '\n' ' ')" >> $GITHUB_OUTPUT
          echo "missing_json_files=$(echo $missing_json_files | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Log Missing Files
        run: |
          echo "Markdown Files Missing: ${{ steps.check_missing.outputs.missing_md_files }}"
          echo "JSON Files Missing: ${{ steps.check_missing.outputs.missing_json_files }}"

      - name: Read prompt from file
        id: prompt
        run: |
          echo 'prompt<<EOF' >> $GITHUB_OUTPUT
          cat .github/workflows/prompt.txt >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Run GPT Translate
        uses: 3ru/gpt-translate@v1.2.2
        with:
          apikey: ${{ secrets.API_KEY }}
          model: ${{ secrets.LLM_MODEL }}
          temperature: ${{ secrets.TEMPERATURE }}
          inputFiles: "${{ steps.check_missing.outputs.missing_md_files }}${{ steps.check_missing.outputs.missing_json_files }}"
          outputFiles: "docs/cn/**/*.{md,json}"
          languages: "Simplified-Chinese"
          prompt: "${{ steps.prompt.outputs.prompt }}"
          basePath: ${{ secrets.BASE_URL }}
